services:
  todoapp.api:
    image: ${DOCKER_REGISTRY-}todoappapi
    build:
      context: .
      dockerfile: TodoApp.Api/Dockerfile
    depends_on:
      - rabbitmq
      - mailhog
      - minio
      - postgres
    environment:
      - Email__SmtpServer=mailhog
      - Email__SmtpPort=1025
      - Email__EnableSsl=false
      - ConnectionStrings__RabbitMQ=rabbitmq
      - AWS__ServiceURL=http://minio:9000
    ports:
      - "5001:80"
      - "5002:443"
    secrets:
      - masstransit_rabbitmq_password
      - minio_secret_key
      - postgres_password 
      - jwt_secret_key

  todoapp.emailworker:
    image: ${DOCKER_REGISTRY-}todoappemailworker
    build:
      context: .
      dockerfile: TodoApp.EmailWorker/Dockerfile
    depends_on:
      - rabbitmq
      - mailhog
      - postgres
    environment:
      - Email__SmtpServer=mailhog
      - Email__SmtpPort=1025
      - Email__EnableSsl=false
      - MassTransit__RabbitMQ__Host=rabbitmq
    secrets:
      - masstransit_rabbitmq_password
      - db_todo_user_password

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
  
  minio:
    image: quay.io/minio/minio 
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD_FILE: /run/secrets/minio_root_password
    secrets:
      - minio_root_password
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  postgres:
    image: postgres:16
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=todo_db
      - POSTGRES_USER=todo_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password 
    secrets:
      - postgres_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./TodoApp.Data/GeracaoBancoDados:/docker-entrypoint-initdb.d

volumes:
  rabbitmq_data:
  minio_data:
  postgres_data:


